### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by havrikov** [vsch/flexmark-java#198]
When parsing the attached file a `StringIndexOutOfBoundsException` is thrown. 
[flexmark_sioobe.zip](https://github.com/vsch/flexmark-java/files/1691938/flexmark_sioobe.zip)
Kotlin code to reproduce assuming the string `x` contains the file contents:  
`Parser.builder().extensions(listOf(AbbreviationExtension.create())).build().parse(x)`  

Should the input be invalid Markdown, an `IllegalArgumentException` is more appropriate.

**Comment by vsch** [comment]
@havrikov, thank you for the heads up.

I will take a look at it. I am preparing a new release so it should get fixed shortly.

**Comment by vsch** [comment]
@havrikov, there is no invalid markdown. That's what makes it so complex to work with.

I tried it on the pre-release build I am working with, in Java because I cannot use Kotlin for the project (you had to mention Kotlin to rub it in) I cannot even use Java 8, to be 7 compatible.

However, it works.

Can you please try it in your setup. Here is the equivalent Java as a ready console app. I want to know for sure it is a bug I already fixed.

If you get an exception, a stack trace printout would help.

```
import com.vladsch.flexmark.ast.Node;
import com.vladsch.flexmark.ext.abbreviation.AbbreviationExtension;
import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;

import java.util.Arrays;

public class Issue198 {
    public static void main(String[] args) {
        String input = "[![ReportCard][ReportCard-Image]][ReportCard-URL] \n" +
                "[![Build][Build-Status-Image]][Build-Status-URL] \n" +
                "\n" +
                "[ReportCard-URL]: https://goreportcard.com/report/jonaswouters/goclerk\n" +
                "[ReportCard-Image]: https://goreportcard.com/badge/jonaswouters/goclerk\n" +
                "[Build-Status-URL]: https://travis-ci.org/jonaswouters/goclerk\n" +
                "[Build-Status-Image]: https://travis-ci.org/jonaswouters/goclerk.svg?branch=master\n";

        Parser parser = Parser.builder().extensions(Arrays.asList(AbbreviationExtension.create())).build();

        Node node = parser.parse(input);

        HtmlRenderer renderer = HtmlRenderer.builder().extensions(Arrays.asList(AbbreviationExtension.create())).indentSize(4).build();
        System.out.println(renderer.render(node));
    }
}
```

**Comment by havrikov** [comment]
What you wrote works for me, but I reduced my original input and can still reproduce the issue as follows (on version `0.28.32`):

```
import com.vladsch.flexmark.ext.abbreviation.AbbreviationExtension;
import com.vladsch.flexmark.parser.Parser;

import java.util.Collections;

public class Issue198 {

  public static void main(String[] args) {
    Parser parser = Parser.builder().extensions(Collections.singletonList(AbbreviationExtension.create())).build();
    parser.parse("\n*[]:a");
  }
}
```

**Comment by vsch** [comment]
@havrikov, sorry about the code I used. I don't know where that came from. I thought I grabbed the unzipped file you sent but it was some other sample.

Yes, I can duplicate this. Abbreviation definitions with a blank abbreviation cause the exception.

**Comment by vsch** [comment]
@havrikov, new release has this fixed. One caution is that there was an API change in the attribute provider factory and html id generator factory to allow re-use of these between HTML and Docx Renderers. Previously `NodeRendererContext` was passed, now `LinkResolverContext`. Access to options is still available. Should not affect code beyond class name change for the parameters.

see [VERSION.md](https://github.com/vsch/idea-multimarkdown/blob/master/test/data/performance/VERSION.md) for details.
