### ISSUE TITLE
Translation Helper bugs

### ISSUE THREAD

**Issue by heyuxian** [vsch/flexmark-java#349]
**Describe the bug** 
When the URL contains an anchor, the Translation Helper API does not render the URL properly.

* [x] `Parser`
* [ ] `HtmlRenderer`
* [x] `Formatter`
* [ ] `FlexmarkHtmlParser`
* [ ] `DocxRenderer`
* [ ] `PdfConverterExtension`
* [ ] extension(s)

**To Reproduce**

**Test Code:**
- refer: https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/TranslationSample.java#L57

Just add an anchor to the URL:
   ```
final String markdown = "This is [*Sparta*](http://sparta.com)";
=>
final String markdown = "This is [*Sparta*](http://sparta.com#anchor)";
   ```
----

**Resulting Output** 
```shell
This is [*Sparta*](http://sparta.com#anchor)
--------------------------
<<<*Sparta*
>>>*sPaARTaA*
<<<This is [_1_](_2_#_1_)
>>>thiIS iIS [_1_](_2_#_1_)
--------------------------
thiIS iIS [*sPaARTaA*](http://sparta.com#_1_)
```

**Comment by vsch** [comment]
@heyuxian, thank you for catching this. It is an omission in handling anchors for links which are not self-references to headings in the document. If the link has a page ref and an anchor then the anchor is left as the translation reference instead of being restored to original text.

I updated the code in the master branch and releasing a new version.

Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by heyuxian** [comment]
@vsch Thank you for solving this issue, but I found that there is still a problem when mixing the code block and anchor. 
**markdown**
```
\```java
  System.out.println("Hello world");
\```
This is [Sparta](http://sparta.com#anchor)
```

**translatingTexts**
```
\```_1_ <== (1)
_2_
\```
This is [_3_](_4_#_1_) <== (1)
```

**translatedTexts**
```
\```anchor <== (1)
System.out.println("Hello world");
\```
This is [Sparta](http://sparta.com#anchor) <== (1)
```

> please ignore `\`, Just to escape the code block.

**Comment by vsch** [comment]
@heyuxian, I got a notification with your other issue of anchor overwriting other non-translating text. Which for some reason disappeared from GitHub but I can confirm this is a bug. Anchor ids were tracked separately but their text was put into non-translating text map. They need their own map which is now implemented and will be released shortly.

Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by vsch** [comment]
Missing post:

    ```java
      System.out.println("Hello world");
    ```
    This is [Sparta](http://sparta.com#anchor)

**translatingTexts**

    ```_1_ <== (1)
    _2_
    ```
    This is [_3_](_4_#_1_) <== (1)

**translatedTexts**

    ```anchor <== (1)
    System.out.println("Hello world");
    ```
    This is [Sparta](http://sparta.com#anchor) <== (1)

**Comment by heyuxian** [comment]
@vsch hi, I found another bug about the Translation Helper. When the `<xxx>` tag is on a separate line (no other characters), it will cause a placeholder error.  please help to check. This is my test code:

```java
MutableDataSet OPTIONS = new MutableDataSet()
            .set(Parser.BLANK_LINES_IN_AST, true)
            .set(Formatter.MAX_TRAILING_BLANK_LINES, 0)
            .set(Parser.EXTENSIONS, Lists.newArrayList(TablesExtension.create(), AnchorLinkExtension.create(),
                AttributesExtension.create()));

        Parser PARSER = Parser.builder(OPTIONS).build();
        Formatter FORMATTER = Formatter.builder(OPTIONS).build();
        String markdown = "# h1\n"
            + "<test>\n"
            + "hello\n"
            + "</test>"
            + "# h2\n";
        // 1. Parse the document to get markdown AST
        Document node = PARSER.parse(markdown);
        System.out.println(markdown);
        // 2. Format the document to get markdown strings for translation
        final TranslationHandler handler = FORMATTER.getTranslationHandler(new HeaderIdGenerator.Factory());
        final String formattedOutput = FORMATTER.translationRender(node, handler, RenderPurpose.TRANSLATION_SPANS);
        System.out.println(formattedOutput);
        // 3. Get the strings to be translated from translation handler
        final List<String> translatingTexts = handler.getTranslatingTexts();

        // 4. Have the strings translated by your translation service of preference
        final ArrayList<CharSequence> translatedTexts = new ArrayList<>(translatingTexts.size());
        // 5. Set the translated strings in the translation handler
        handler.setTranslatedTexts(translatingTexts.stream().collect(Collectors.toList()));
        // 6. Generate markdown with placeholders for non-translating string and out of context translations
        // the rest will already contain translated text
        final String partial = FORMATTER.translationRender(node, handler, RenderPurpose.TRANSLATED_SPANS);
        // 7. Parse the document with placeholders
        Node partialDoc = PARSER.parse(partial);
        // 8. Generate the final translated markdown
        final String translated = FORMATTER.translationRender(partialDoc, handler, RenderPurpose.TRANSLATED);
        System.out.println(translated);
```

**formattedOutput**
```shell
# h1

<__1_> <== 
```

**translated **
```shell
# h1

<__1_>  <== 
```

**Comment by heyuxian** [comment]
sorry, It's my bug, I will close this issue.
